
dbcc shrinkfile(2, TRUNCATEONLY )
/*
ALTER DATABASE FALCON_SRF_Credit SET RECOVERY SIMPLE WITH NO_WAIT

DBCC SHRINKFILE(N'FALCON_SRF_D02_Log1', 1)

CHECKPOINT;
GO
CHECKPOINT; -- run twice to ensure file wrap-around
GO


ALTER DATABASE FALCON_SRF_Credit SET RECOVERY FULL WITH NO_WAIT
*/
