drop index AccountInitiation.AccountInitiationAcctID_IDX
drop index AccountIDTAPSAccount.accountNumber
drop index AccountParticipant.AccountParticipant_partyIDX
drop index AcctGroupCoverageGroup.AcctGroupCoverageGroup_CovID
drop index AccountActivity.acctID
drop index AccountCorrespondentProduct.acctID
drop index AccountCreditData.acctID
drop index AccountFuturesProduct.acctID
drop index AccountFXProduct.acctID
drop index AccountIDTAPSAccount.acctID
drop index AccountInitiation.acctID
drop index AccountIRAProduct.acctID
drop index AccountOptionsProduct.acctID
drop index AccountPortfolioSweepProduct.acctID
drop index AccountProductData.acctID
drop index AccountRegionalData.acctID
drop index AccountTokyoProduct.acctID
drop index BinaryAccountRelationship.acctID
drop index ClearingBrokerReference.acctID
drop index DIAlternateDeliveryCode.acctID
drop index DIDTC.acctID
drop index DIGovernment.acctID
drop index DIPhysical.acctID
drop index TAPSAccount.acctID
drop index TAPSAccount.acctIDLoad
drop index BinaryAccountRelationship.assocAcctNubAcctNum
drop index PartyAttribute.AtIDPID
drop index BusinessDefAccount.BusinessDefAccount_acctIDX
drop index E3ResourcesToResourceGroups.C_ResourcesToResourceGroups
drop index TAPSGeneralAddressInactive.lastUpdateTS
drop index Membership.Membership_exchMembIDX
drop index Membership.Membership_partyExchIDX
drop index CoverageGroupRole.parentGroupRoleIDX
drop index PartyExchange.PartyExchange_partyIDX
drop index PartyHierarchy.PartyHierarchy_childIDX
drop index PartyAttribute.PAVer
drop index PartyAttribute.PIDAtIDRN
drop index AttributeValidation.PKAttributeValidation
drop index TIDWorkgroup.primAcctSecGrCode_idx
drop index TAPSAccount.RegionScopeStatusIDX
drop index TAPSAccount.ScopeStatusIDX
drop index TAPSGeneralAddressInactive.TAPSGAInactiveAcctID_IDX
drop index TAPSGeneralAddressTypeInactive.TAPSGATI_AccNumSysType
drop index TradingNameDefinitionDetail.TNDIDTNIV
drop index TNDIdentifierDivision.TNIDTNDIDTITM
drop index TNLClientIdentifierCode.TNLClientIdentifierCodeAK
drop index TradingNameAudit.TradingNameAudit_IDX
drop index TIDUser.userlogin_idx
drop index TIDUser.workgroupName_idx
drop index TIDWorkgroup.workgroupName_idx
drop index GroupDesiCoverage.XIF1GroupDesiCoverage
drop index TradingNameLocBusDef.XIF1TradingNameLocBusDef
drop index TradingNameLocBusDef.XIF2TradingNameLocBusDef
drop index TNLBDOrderCapacity.XIF3TNLBDOrderCapacity
drop index TradingNameLocBusDef.XIF3TradingNameLocBusDef
drop index PartySite.XsiteDunsPartySite
drop index TAPSGeneralAddressTypeInactive.lastUpdateTS
drop index t1.nc1
go
